### ISSUE TITLE
Request to include function hb_ntp_GetTimeUTC() from hb34/contrib/hbmisc

### ISSUE THREAD

**Issue by mhsabado** [marcosgambeta/harbourpp-v1#2]
Hi Marcos,

Would it be possible to include the above function in HarbourPP?

Thanks,
Mario

**Comment by marcosgambeta** [comment]
Done.
https://github.com/marcosgambeta/harbourpp-v1/commit/19256785149a027c82e05d5da5765449121ccd5f

**Comment by mhsabado** [comment]
Many thanks Marcos!
