### ISSUE TITLE
Error building latest under MSVC64/32

### ISSUE THREAD

**Issue by mhsabado** [marcosgambeta/harbourpp-v1#6]
Hi Marcos,

I encountered the following error when building under MSVC64/32.  It proceeds though using Mingw64 and builds successfully.

Thanks,
Mario
************************************************************************
C:\harbourpp\src\vm\classes.cpp(1934): warning C4244: '=': conversion from 'HB_SYMCNT' to 'HB_USHORT', possible loss of data
C:\harbourpp\src\vm\set.cpp(472): warning C4805: '!=': unsafe mix of type 'bool' and type 'HB_BOOL' in operation
C:\harbourpp\src\vm\memvars.cpp(1096): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1097): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1143): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1145): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1176): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1178): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1209): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\memvars.cpp(1211): error C2039: 'size_t': is not a member of 'std'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stddef.h(23): note: see declaration of 'std'
C:\harbourpp\src\vm\extend.cpp(949): warning C4312: 'reinterpret_cast': conversion from 'int' to 'void *' of greater size
win-make[3]: *** [../../../../../config/rules.mk:109: hvmall.obj] Error 2
win-make[2]: *** [../../config/lib.mk:64: descend] Error 2
win-make[1]: *** [../config/dir.mk:71: vm] Error 2
win-make: *** [config/dir.mk:71: src] Error 2
*******************************************************************

**Comment by marcosgambeta** [comment]
Please, try after this commit:
https://github.com/marcosgambeta/harbourpp-v1/commit/062c1ce5bad66f24f6f28d81cb51481c65de08f6

**Comment by mhsabado** [comment]
Already fixed after latest commit.  Many thanks Marcos!

Best regards,
Mario
