### ISSUE TITLE
Error building after latest commits

### ISSUE THREAD

**Issue by mhsabado** [marcosgambeta/harbourpp-v1#7]
Hi Marcos,

I have the following error when building the latest commits.

Thanks,
Mario

MSVC2022
*******************************
C:\harbourpp\src\vm\estack.cpp(1313): error C2059: syntax error: '}'
C:\harbourpp\src\vm\estack.cpp(1307): error C2059: syntax error: 'return'
C:\harbourpp\src\vm\estack.cpp(1309): error C2059: syntax error: 'else'
C:\harbourpp\src\vm\estack.cpp(1310): error C2143: syntax error: missing ';' before '{'
C:\harbourpp\src\vm\estack.cpp(1310): error C2447: '{': missing function header (old-style formal list?)
C:\harbourpp\src\vm\estack.cpp(1313): error C2143: syntax error: missing ';' before '}'
C:\harbourpp\src\vm\estack.cpp(1316): error C2143: syntax error: missing ';' before '{'
C:\harbourpp\src\vm\estack.cpp(1316): error C2447: '{': missing function header (old-style formal list?)
win-make[3]: *** [../../../../../config/rules.mk:109: hvmall.obj] Error 2
win-make[2]: *** [../../config/lib.mk:64: descend] Error 2
win-make[1]: *** [../config/dir.mk:71: vm] Error 2
win-make: *** [config/dir.mk:71: src] Error 2
*******************************

Mingw 8.50
******************************
In file included from ../../../hvmall.cpp:107:
../../../estack.cpp: In function 'HB_ISIZ hb_stackBaseProcOffset(int)':
../../../estack.cpp:1305:68: error: expected ')' before '{' token
   if (iLevel < 0 && (nOffset > 0 || (*hb_stack.pItems)->isSymbol())
      ~                                                             ^
                                                                    )
   {
   ~
../../../estack.cpp:1313:1: error: expected primary-expression before '}' token
 }
 ^
../../../estack.cpp:1313:1: warning: no return statement in function returning non-void [-Wreturn-type]
win-make[3]: *** [../../../../../config/rules.mk:109: hvmall.o] Error 1
win-make[2]: *** [../../config/lib.mk:64: descend] Error 2
win-make[1]: *** [../config/dir.mk:71: vm] Error 2
win-make: *** [config/dir.mk:71: src] Error 2
******************************

**Comment by marcosgambeta** [comment]
Please,, compile again after:
https://github.com/marcosgambeta/harbourpp-v1/commit/e65bb829bd5b70cc2ca0c6161c3cef5f5516d070

**Comment by mhsabado** [comment]
Hi Marcos,

It was now compiled successfully.  Thank you!

Best regards,
Mario
